###########################
# source from "~/.bashrc"

umask 0000

# Local PATH:
export PATH="~/bin:$PATH"

# CGRU folder:
if [ "$PWD" == "$HOME" ]; then
	[ -d /data/cgru ] && cd /data/cgru
	[ -d /cgru ] && cd /cgru
else
	wd=`echo "$PWD" | sed "s/\/data//g"`
	[ -d "$wd" ] && cd "$wd"
fi

alias nv='nvim'

# TANK
alias sst='ssh -i /home/timurhai/.ssh/id_rsa u5fx.ru -p 20221'
alias sstp='ssh -i /home/timurhai/.ssh/id_rsa -L 52000:10.77.12.4:51000 -L 3690:10.77.12.4:3690 u5fx.ru -p 20221'


