call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
Plug 'preservim/tagbar'
Plug 'preservim/nerdtree'
"Plug 'Shougo/deoplete.nvim'
"Plug 'valloric/youcompleteme'
Plug 'kien/rainbow_parentheses.vim'
Plug 'junegunn/fzf.vim'
call plug#end()

"let g:deoplete#enable_at_startup = 1

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces


:set noexpandtab
:set tabstop=4
:set shiftwidth=4
:autocmd FileType python set expandtab

" Indentation
:set autoindent
":set smartindent
:set cindent
" Prevent # to be indented
:set cinkeys-=0#
:set indentkeys-=0#

:map <F7> :tabnew<CR>
:imap <F7> :tabnew<CR>

:map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>

:set wildmode=longest,list,full
:set wildmenu

:map <F4> :tabe %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
:imap <F4> :tabe %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>


"Syntax Highlighting
:syn clear
:color desert

":autocmd Syntax * syn match _bracket "[(){}\[\]]"
:autocmd Syntax cpp syn match _symbol "[~!@$%^&<>,\.:;=\-?\+\*]"

:hi Number ctermfg=DarkMagenta
:hi cNumber ctermfg=DarkMagenta
:hi String ctermfg=Gray
:hi cString ctermfg=Gray
:hi _bracket ctermfg=DarkRed
:hi _symbol ctermfg=DarkGreen
:hi SpellBad ctermbg=DarkRed

"let g:syntastic_rst_checkers=['sphinx']

":syntax on

